steps:
  - name: 'hashicorp/terraform'
    args:
      - 'init'
  - name: 'hashicorp/terraform'
    args: ['plan', '-var', 'project_id=$PROJECT_ID']
  - name: 'hashicorp/terraform'
    args: ['apply', '-var', 'project_id=$PROJECT_ID', '-auto-approve']
  - name: 'hashicorp/terraform'
    args: ['destroy', '-var', 'project_id=$PROJECT_ID', '-auto-approve']
